In [1]:
# This chunk of code make it possible to use src functions
import sys
import os
module_path = os.path.abspath(os.path.join('../src'))

if module_path not in sys.path:
    sys.path.append(module_path)
    
from dsproject import dsproject

dsp = dsproject()

In [2]:
dsp.data_directory = os.path.join(os.path.dirname(dsp.data_directory), '201510_201610')

In [4]:
df = dsp.read_data('CST_DIM', nrows=1000)

In [5]:
df.head()

,HASH_IP_ID,EFF_DT,END_DT,BRTH_DT,ESTB_DT,DEATH_DT,SALUT_TH,SALUT_EN,IDENTN_TP_ID,IDENTN_TP_SHRT_DSC,...,CTC_ADR_RGON_SHRT_DSC,CTC_ADR_PROV_TX,KBNK_EMPE_ID,APL_CC_MO_INCM_AMT,HSHOLD_NBR_DPND_CHL,CC_STMT_RET_RSN_ID,CC_STMT_RET_RSN_SHRT_DSC,EFF_CST_DT,END_CST_DT,ORG_REV_AMT
0,-2863372291240844444,2014-02-13,9999-12-31,1973-02-15,NaN,NaN,นาย,MR.,11,บัตรประชาชน,...,เหนือตอนบน,ลำพูน,0.0,16202.0,NaN,0,NaN,2006-08-02,NaN,0
1,-614678066021058079,2014-02-13,9999-12-31,1972-02-12,NaN,NaN,น.ส.,MS.,11,บัตรประชาชน,...,ตะวันออกเฉียงเหนือตอนล่าง,นครราชสีมา,0.0,20000.0,NaN,0,NaN,2002-11-06,NaN,0
2,-8163542081405060565,2014-04-03,9999-12-31,1983-10-22,NaN,NaN,นาย,MR.,11,บัตรประชาชน,...,กรุงเทพฯ และ ปริมณฑล,กทม.,0.0,23557.0,NaN,0,NaN,2011-02-26,NaN,0
3,8866124540733062802,2013-02-27,9999-12-31,1976-09-30,NaN,NaN,นาย,MR.,11,บัตรประชาชน,...,ตะวันตก,สมุทรสาคร,0.0,220317.0,NaN,0,NaN,2007-11-06,NaN,0
4,-5200758527377527629,2013-02-27,9999-12-31,1972-06-02,NaN,NaN,นาย,MR.,11,บัตรประชาชน,...,ใต้ตอนล่าง,ปัตตานี,0.0,58000.0,NaN,0,NaN,2011-03-19,NaN,0

In [20]:
delete_columns = ['RACE_SHRT_DSC', 'CST_SEG_SHRT_DSC', 'ORIG_BR_SHRT_DSC',
                   'CTC_ADR_LO_SHRT_DSC', 'CST_TP_SHRT_DSC', 'GND_SHRT_DSC', 'OFFC_ADR_LO_SHRT_DSC',
                   'OFFC_ADR_RGON_SHRT_DSC', 'CST_LCS_SHRT_DSC', 'ED_LVL_SHRT_DSC', 'CR_ASES_SHRT_DSC',
                   'IP_LCS_SHRT_DSC', 'CTC_ADR_RGON_SHRT_DSC', 'KBNK_IDY_CL_SHRT_DSC', 'BOT_IDY_CL_SHRT_DSC',
                   'MAR_ST_SHRT_DSC', 'OCP_SHRT_DSC', 'CST_DUAL_SEG_SHRT_DSC', 'IP_TP_SHRT_DSC',
                   'INCM_RNG_SHRT_DSC', 'OCP_GRP_SHRT_DSC', 'IDENTN_TP_SHRT_DSC', 'IDV_PROF_TP_SHRT_DSC',
                   'NAT_SHRT_DSC', 'CTC_ADR_ZIP_CODE', 'OFFC_ADR_ZIP_CODE', 'DRCTR_SHRT_DSC', 'MGR_SHRT_DSC',
                   'OFFC_ADR_PROV_TX', 'SALUT_TH', 'RM_SHRT_DSC', 'CTC_ADR_PROV_TX', 'SEG_HD_SHRT_DSC']

In [21]:
df = df.drop(delete_columns, axis=1)

for column in df.columns:
    print(column)
    u = df[column].unique().tolist()
    if len(u) > 5:
        print(u[0:5])
    else:
        print(u)

HASH_IP_ID
[-2863372291240844444, -614678066021058079, -8163542081405060565, 8866124540733062802, -5200758527377527629]
EFF_DT
['2014-02-13', '2014-04-03', '2013-02-27', '2013-06-02', '2013-06-09']
END_DT
['9999-12-31']
BRTH_DT
['1973-02-15', '1972-02-12', '1983-10-22', '1976-09-30', '1972-06-02']
ESTB_DT
[nan, '1950-02-01', '1977-06-06', '1982-12-16', '1978-02-03']
DEATH_DT
[nan, '2010-02-22']
SALUT_EN
['MR.                                     ', 'MS.                                     ', 'MRS.                                    ', nan, 'POL.SUB.LT.                             ']
IDENTN_TP_ID
[11, 12]
IP_LCS_TP_ID
[1]
IP_LCS_EFF_DT
[nan]
CST_LCS_TP_ID
['C']
CST_LCS_EFF_DT
[nan]
IDV_LCS_TP_ID
[nan, 'Y ']
IDV_LCS_SHRT_DSC
[nan]
IDV_LCS_EFF_DT
[nan]
IP_MRG_ST_TP_ID
[nan]
IP_MRG_ST_SHRT_DSC
[nan]
IP_MRG_DT
[nan]
CR_ASES_ID
['G', 'B']
CST_SEG_ID
['MI', 'XS', 'AF', 'SO', 'SM']
CST_SUB_SEG_ID
['M2', 'L2', 'K2', 'L3', '01']
CST_SUB_SEG_SHRT_DSC
[nan]
CST_DUAL_SEG_ID
['MI', 'AF']
CST_DUAL_SUB_SEG_ID
['M2', 'L2', 'K2', 'L3', 'K3']
CST_DUAL_SUB_SEG_SHRT_DSC
[nan]
CST_TP_ID
[704, 702, 1003, 703]
ED_LVL_ID
['04', '01', '05', '02', '03']
GND_ID
[1, 2]
INCM_RNG_ID
['04', '08', '06', '05', '03']
MAR_ST_TP_ID
['2', '1', '3', '4', nan]
NAT_ID
['TH ', 'GB ', 'NL ', 'US ', 'AU ']
RLG_ID
[nan, '  ']
RLG_SHRT_DSC
[nan]
RACE_ID
['TH ', 'GB ', 'NL ', nan, 'AU ']
OCP_ID
[4, 11, 7, 9, 1]
OCP_GRP_ID
['09', '01', nan, '06', '13']
IDV_PROF_TP_ID
['          ', '17        ', '15        ', '02        ', '12        ']
RM_ID
[nan, 374239.0]
MGR_ID
[nan, 374239.0]
DRCTR_ID
[nan, 218089.0]
SEG_HD_ID
[nan, 120244.0]
CST_SPRS_F
[nan]
CST_SPRS_SHRT_DSC
[nan]
HM_PH_SPRS_F
[nan]
HM_PH_SPRS_SHRT_DSC
[nan]
OFFC_PH_SPRS_F
[nan]
OFFC_PH_SPRS_SHRT_DSC
[nan]
MBL_PH_SPRS_F
[nan]
MBL_PH_SPRS_SHRT_DSC
[nan]
EMAIL_SPRS_F
[nan]
EMAIL_SPRS_SHRT_DSC
[nan]
DRC_MAIL_SPRS_F
[nan]
DRC_MAIL_SPRS_SHRT_DSC
[nan]
TELE_MKT_SPRS_F
[nan]
TELE_MKT_SPRS_SHRT_DSC
[nan]
SMS_SPRS_F
[nan]
SMS_SPRS_SHRT_DSC
[nan]
OFFC_ADR_UNCTC_F
[nan]
OFFC_ADR_UNCTC_RSN_ID
[nan]
OFFC_ADR_UNCTC_RSN_SHRT_DSC
[nan]
OFFC_ADR_UNCTC_STMP_DT
[nan]
WRK_ADR_UNCTC_F
[nan]
WRK_ADR_UNCTC_RSN_ID
[nan]
WRK_ADR_UNCTC_RSN_SHRT_DSC
[nan]
WRK_ADR_UNCTC_STMP_DT
[nan]
CTC_ADR_UNCTC_F
[nan]
CTC_ADR_UNCTC_RSN_ID
[nan]
CTC_ADR_UNCTC_RSN_SHRT_DSC
[nan]
CTC_ADR_UNCTC_STMP_DT
[nan]
HM_PH_UNCTC_F
[nan]
HM_PH_UNCTC_RSN_ID
[nan]
HM_PH_UNCTC_RSN_SHRT_DSC
[nan]
HM_PH_UNCTC_STMP_DT
[nan]
WRK_PH_UNCTC_F
[nan]
WRK_PH_UNCTC_RSN_ID
[nan]
WRK_PH_UNCTC_RSN_SHRT_DSC
[nan]
WRK_PH_UNCTC_STMP_DT
[nan]
MBL_PH_UNCTC_F
[nan]
MBL_PH_UNCTC_RSN_ID
[nan]
MBL_PH_UNCTC_RSN_SHRT_DSC
[nan]
MBL_PH_UNCTC_STMP_DT
[nan]
FAX_UNCTC_F
[nan]
FAX_UNCTC_RSN_ID
[nan]
FAX_UNCTC_RSN_SHRT_DSC
[nan]
FAX_UNCTC_STMP_DT
[nan]
PSN_E_MAIL_UNCTC_F
[nan]
PSN_E_MAIL_UNCTC_RSN_ID
[nan]
PSN_E_MAIL_UNCTC_RSN_SHRT_DSC
[nan]
PSN_E_MAIL_UNCTC_STMP_DT
[nan]
WRK_E_MAIL_UNCTC_F
[nan]
WRK_E_MAIL_UNCTC_RSN_ID
[nan]
WRK_E_MAIL_UNCTC_RSN_SHRT_DSC
[nan]
WRK_E_MAIL_UNCTC_STMP_DT
[nan]
MBL_PH_F
['Y', 'N']
E_MAIL_F
['N', 'Y']
CONSND_KA_F
[nan]
CONSND_KF_F
[nan]
CONSND_KL_F
[nan, 'Y', 'N']
CONSND_KS_F
[nan, 'Y']
KBNK_STFF_F
['N', 'Y', nan]
PRVT_WLTH_F
['N']
BOT_IDY_CL_ID
[10060000, 10050000, 3060102, 10020000, 5011702]
KBNK_IDY_CL_ID
[24, 28, 7, 22, 2]
ORIG_BR_NBR
[997, 439, 970, 184, 743]
IP_TP_ID
['I']
OFFC_ADR_LO_ID
['UPC', 'BKK', nan]
OFFC_ADR_RGON_ID
['NU', 'XL', 'CB', 'CW', 'SL']
CTC_ADR_LO_ID
['UPC', 'BKK', nan]
CTC_ADR_RGON_ID
['NU', 'XL', 'CB', 'CW', 'SL']
KBNK_EMPE_ID
[0.0, nan]
APL_CC_MO_INCM_AMT
[16202.0, 20000.0, 23557.0, 220317.0, 58000.0]
HSHOLD_NBR_DPND_CHL
[nan]
CC_STMT_RET_RSN_ID
[0, 3, 5]
CC_STMT_RET_RSN_SHRT_DSC
[nan]
EFF_CST_DT
['2006-08-02', '2002-11-06', '2011-02-26', '2007-11-06', '2011-03-19']
END_CST_DT
[nan]
ORG_REV_AMT
[0]

In [23]:
df = dsp.read_data('EDW_SUM_CC_AR_BHVR_SCOR', nrows=1000)

In [24]:
df.head()

,HASH_AR_ID,HASH_IP_ID,POSN_DT,CC_TP_ID,BILL_CYC_ID,CRN_DLQ_ST,LAST_PRCH_DYS,LAST_DLQ_MO,LAST_PYMT_DYS,AR_AGE_MO,...,NBR_OLMT_ST_P3M,NBR_OLMT_ST_P6M,AV_CASH_ADV_AMT_P6M,AV_PYMT_RTO_P6M,AV_LMT_USG_RTO_P6M,NBR_DLQ_ST_60_89_P6M,NBR_FULL_PYMT_P6M,NBR_PART_PYMT_P6M,IS_INACT_ST_P8M_F,CST_WRST_DLQ_ST
0,-5098227571238192422,-467094571027012660,2015-04-30,62,5,1,671,0,15,53,...,0,0,999.0,0.0,0.00,0,0,6,1,1
1,-5964985432695974342,-839014941698514011,2015-04-30,971,20,0,10,999,16,51,...,0,0,0.0,100.0,0.64,0,4,0,0,0
2,-1606054327765779009,4104565898471944259,2015-04-30,934,20,Z,999,999,999,4,...,0,0,999.0,999.0,5.74,0,0,0,1,B
3,-171494769172806018,876594190889525986,2015-04-30,994,25,Z,217,7,16,100,...,0,0,999.0,0.0,-1.07,0,0,0,0,B
4,-1018883884800917793,4532442355235274885,2015-04-30,971,25,Z,172,999,106,8,...,0,0,0.0,100.0,1.08,0,2,0,0,B

In [25]:
for column in df.columns:
    print(column)
    u = df[column].unique().tolist()
    if len(u) > 5:
        print(u[0:5])
    else:
        print(u)

HASH_AR_ID
[-5098227571238192422, -5964985432695974342, -1606054327765779009, -171494769172806018, -1018883884800917793]
HASH_IP_ID
[-467094571027012660, -839014941698514011, 4104565898471944259, 876594190889525986, 4532442355235274885]
POSN_DT
['2015-04-30']
CC_TP_ID
[62, 971, 934, 994, 939]
BILL_CYC_ID
[5, 20, 25, 17, 10]
CRN_DLQ_ST
['1', '0', 'Z', 'B', '2']
LAST_PRCH_DYS
[671, 10, 999, 217, 172]
LAST_DLQ_MO
[0, 999, 7, 2, 1]
LAST_PYMT_DYS
[15, 16, 999, 106, 19]
AR_AGE_MO
[53, 51, 4, 100, 8]
BAL_LMT_PCT
[0.0, 0.18, -3.84, 67.73, 0.07]
BAL_AV_LMT_3MO_PCT
[0.0, 0.67, -3.84, 28.54, 0.94]
CASH_ADV_AV_LMT_3MO_PCT
[0.0, -3.84, -0.24, 30.45, -0.21]
PYMT_PREV_BAL_AV_3MO_PCT
[0.0, 100.0, 999.0, 769.57, 78.1]
NBR_DYS_NOT_PY_3DYS_LAST_1MO
[0, 1, 2, 3]
NBR_DYS_NOT_PY_8DYS_LAST_1MO
[0, 2, 1, 7, 3]
NBR_DYS_NOT_PY_30DYS_LAST_3MO
[0, 2, 1, 3]
NBR_DYS_NOT_PY_30DYS_LAST_8MO
[0, 1, 3, 2, 5]
NBR_DYS_NOT_PY_60DAY_LAST_6MO
[0, 1]
CARD_TP
[1, 2, 3, 4]
CARD_LVL
['C', 'P', 'G', '9']
AR_APL_SCOR
[0]
CST_WST_SCOR
[959, 25, 15, 36, 0]
CST_WST_RSK_IND
[98, 12, 11, 9, 10]
CST_WST_RSK_GRD_IND
[98, 5, 4, 0, 1]
CST_BAL_AV_LMT_3MO_PCT
[0.0, 0.33, 8.01, -1.09, 0.85]
AR_RSK_SCOR_ID
['LU', 'HU']
AR_RSK_SCOR
[959, 1061, 1036, 962, 986]
AR_RSK_GRD
[98, 5, 4, 3, 2]
AR_RSK_PERF_IND
[98, 12, 9, 10, 11]
AR_GOOD_BAD_SCOR
[15, 2, 14, 12, 13]
AR_GOOD_BAD_CODE
['G', 'X', 'I', 'B']
NBR_DLQ_ST_30_59_P3M
[0, 1, 2, 3, 6]
NBR_DLQ_ST_1_29_P3M
[0, 1, 2, 4, 3]
NBR_OLMT_ST_P3M
[0, 3, 1, 2]
NBR_OLMT_ST_P6M
[0, 3, 6, 2, 1]
AV_CASH_ADV_AMT_P6M
[999.0, 0.0, 55.53, 10.53, 80.0]
AV_PYMT_RTO_P6M
[0.0, 100.0, 999.0, 515.21, 112.75]
AV_LMT_USG_RTO_P6M
[0.0, 0.64, 5.74, -1.07, 1.08]
NBR_DLQ_ST_60_89_P6M
[0, 1, 2]
NBR_FULL_PYMT_P6M
[0, 4, 2, 5, 1]
NBR_PART_PYMT_P6M
[6, 0, 3, 2, 1]
IS_INACT_ST_P8M_F
[1, 0]
CST_WRST_DLQ_ST
['1', '0', 'B', '2', '3']

In [26]:
df = dsp.read_data('EDW_SOR_CC_AR', nrows=1000)

In [27]:
for column in df.columns:
    print(column)
    u = df[column].unique().tolist()
    if len(u) > 5:
        print(u[0:5])
    else:
        print(u)

HASH_IP_ID
[1285159519081554241, -3283794275082147490, 6313486906264742555, 535795785686208776, -1813420594356074564]
HASH_AR_ID
[-6382578461624446232, 7972001686616636889, 200434861221458160, -6172311574706402806, -3162398376566542078]
HASH_LPM_CST_ID
[-4486709394732844169, -2554121118804933540, 9097373434166979169, -1415740768575822342, 134000336148187462]
POSN_DT
['2015-02-28', '2016-12-31']
AR_LVL_IND
[0]
OTSND_BAL_AMT
[21326.87, 9516.38, 0.0, 1368.93, 104206.19]
ACR_INT_AMT
[264.1, 113.0, 0.0, 8.36, 742.23]
AR_SCR_TP_ID
['U']
FSVC_TMT_OUTC_TP_ID
[nan]
FSVC_LMT_TP_ID
['F']
FSVC_RPYMT_TP_ID
['A']
RSTC_DFCLT_LVL_ID
[nan]
FSVC_PDA_SEG_ID
[1, 0, 2, 3, 7]
FSVC_UTLZ_SEG_ID
[nan]
FSVC_UTLZ_RNG_ID
[nan]
PTNL_ESR_RNG_ID
[nan]
PHOTO_F
[nan, 0.0]
CC_TP_ID
[994, 819, 827, 829, 934]
PD_ID
[nan]
CST_TP_ID
[704, 702, 703, 1003, 707]
CST_ORG_NBR
[1]
AU_ID
[1421036, 1421041, 1421040, 1421030, 1421035]
ALT_CST_ORG_NBR
[0, 1]
ALT_SRC_CST_ID
[0, 1000000009127885, 1000000016881417, 1000000022215675, 1000000023393638]
BILL_CYC_ID
[17, 5, 25, 20, 10]
BLC_CODE_ID
[nan, 'U', 'X', 'L', 'J']
BLC_DT
['2013-02-04', '2014-11-27', '2011-10-31', '2013-02-06', nan]
ALT_BLC_CODE_ID
[nan, 'T', 'P', 'L', 'R']
ALT_BLC_CODE_DT
['2015-02-05', '2015-02-10', '2011-04-21', '2013-02-01', '2011-12-13']
ALT_CST_EXP_DT
[nan]
EFF_DT
['2013-10-31', '2013-04-30', '2010-09-30', '2010-11-30', '2013-05-31']
OPN_DT
['2008-10-19', '2013-04-12', '2010-09-15', '2010-11-16', '2008-05-05']
MAT_DT
['2018-10-31', '2018-04-30', '2015-09-30', '2015-11-30', '2018-05-31']
LAST_PRCH_DT
['2015-02-23', '2015-02-17', '2011-12-05', nan, '2015-02-20']
LAST_ADV_DT
[nan, '2013-08-15', '2008-03-12', '2015-01-28', '2013-12-16']
LAST_CASH_PYMT_DT
['2014-06-30', '2014-12-08', nan, '2014-07-04', '2014-09-01']
LAST_RTL_PYMT_DT
['2015-02-09', '2015-02-10', '2011-12-20', nan, '2015-02-28']
PYMT_DUE_DT
['2015-03-05', '2012-01-20', nan, '2015-03-12', '2015-03-09']
LAST_MNT_DT
['2014-09-01', '2015-02-11', '2014-11-21', '2015-02-14', '2014-12-19']
NBR_RQS
[15, 50, 16, 0, 17]
CARD_TP
[80, 98, 2, 0, 75]
PRJ_ID
[1580, 5098, 1602, 0, 1575]
CHK_AC_NBR
[0, 511042089, 991048405, 2071019279, 101085066]
SVG_AC_NBR
[0, 6022002420, 452905361, 672737788, 1422500853]
MN_PYMT_F
[0, 1]
BNK_AC_NBR
[0, 1122332507, 1042571837, 182889105, 8072185146]
CRN_DUE
[1882.69, 1000.0, 0.0, 1368.93, 30264.24]
TAMT_DUE
[1882.69, 1000.0, 0.0, 1368.93, 30264.24]
CRN_STMT_BAL
[18826.87, 9516.38, 0.0, 1368.93, 131206.19]
PREV_STMT_BAL
[12680.66, 5529.3, 1055.16, 0.0, 10400.93]
ORIG_CCY_ID
['THB']
BR_NBR
[400, 766, 272, 443, 109]
CARD_CGY_ID
[3, 1, 5, 2]
CARD_TP_ID
[58, 93, 78, 75, 74]
IS_PNP_CARD_F
['Y', 'N']
PNP_CARD_ITRV_ID
[5, 2, 4, 3, 1]
CC_ST_ID
[1, 2, 4, 0]
IS_STFF_F
['N', 'Y']
CR_LMT_AMT
[224000.0, 30000.0, 50000.0, 608000.0, 200000.0]
PYMT_MTH_ID
[0, 1]
NBR_PNP_CARD
[7, 2, 5, 10, 4]
RSPL_DEPT_ID
['0', 'G', 'F', '5', '7']
MISC_CODE
['02', 'G3', 'G4', 'G2', '00']
NPL_DT
[0, 201310, 201412, 200002, 199809]
NPL_F
['Y', 'U', 'N']
IS_CARD_VLD_F
['Y', 'N']
COLL_BR_NBR
[777, 999, 111]
CLT_TP_ID
[nan]
IS_CLCB_F
['Y', 'N']
CLOSE_DT
[nan]
CRT_DT
[nan]
OWN_BR
[9975, 9935, 9957, 9962, 9964]
AC_GRP_ID
[1.0, nan, 0.0, 2.0, 3.0]
AFF_CODE
[0, 44, 29, 3, 28]
AFF_MBR_TP_REL_YR
[nan]
AFF_MBR_ORG_GRP_ID
[nan]
AFF_MBR_TP_ID
[0]
AFF_MBR_ORG_ID
[0, 6, 2, 3]
ACT_PYMT_ITRV_ID
[6, 5, 9999, 4, 1]
AMT_RNG_ID
[839, 831, 842, 846, 830]
COLL_RSN_CODE
[nan, 4.0, 2.0, 1.0, 3.0]
DLQ_DAY_ITRV_ID
[8888, 1, 2, 6, 8]
LAST_PYMT_ITRV_ID
[1, 13, 9999, 8888, 6]
COLL_ID
[0]
INT_BILL_NOT_PAID_AMT
[223.21, 132.59, 0.0, 523.8, 175.51]
AUTO_PYMT_AMT
[0.0, 10400.93, 43566.54, 1000.0, 927.69]
NON_AUTO_PYMT_AMT
[12681.0, 5000.0, 0.0, 27000.0, 2500.0]
CRN_CYC_AMT
[2500.0, 0.0, -27000.0, -2500.0, 751.14]
DLQ_DYS
[0, 8, 49, 3, 162]
NBR_MO_SNC_LAST_PYMT
[1, 39, 999, 0, 6]
DLQ_ST_ID1
['B', '1', 'Z', '2', '0']
DLQ_ST_ID2
['B', 'Z', '1', nan, '0']
DLQ_ST_ID3
['B', 'Z', '1', nan, '0']
DLQ_ST_ID4
['B', '0', 'Z', '1', nan]
DLQ_ST_ID5
['B', 'Z', '1', nan, '0']
DLQ_ST_ID6
['B', '2', 'Z', '1', nan]
DLQ_ST_ID7
['B', '0', 'Z', '1', nan]
DLQ_ST_ID8
['B', 'Z', '0', '1', nan]
DLQ_ST_ID9
['B', 'Z', '1', nan, '0']
DLQ_ST_ID10
['B', 'Z', '1', nan, '0']
DLQ_ST_ID11
['B', 'Z', '1', nan, '0']
DLQ_ST_ID12
['B', '0', 'Z', '1', nan]
DLQ_ST_ID13
['B', '2', 'Z', '1', nan]
DLQ_ST_ID14
['B', 'Z', '1', nan, '0']
DLQ_ST_ID15
['B', 'Z', '1', nan, '2']
DLQ_ST_ID16
['B', 'Z', '1', '0', nan]
DLQ_ST_ID17
['1', '2', 'Z', 'B', nan]
DLQ_ST_ID18
['1', 'Z', 'B', nan, '4']
DLQ_ST_ID19
['B', '0', 'Z', '1', nan]
DLQ_ST_ID20
['1', 'B', 'Z', nan, '2']
DLQ_ST_ID21
['B', '2', 'Z', '1', nan]
DLQ_ST_ID22
['B', '0', 'Z', '1', nan]
DLQ_ST_ID23
['1', 'Z', 'B', nan, '2']
DLQ_ST_ID24
['1', nan, 'Z', 'B', '0']
PAST_DUE_AMT
[0.0, 1000.0, 0.21, 6994.53, 4.89]
ACR_INT_RTL_AMT
[264.1, 113.0, 0.0, 8.36, 742.22]
ACR_INT_CASH_ADV_AMT
[0.0, 335.76, 423.45, 25.02, 140.52]
II_AMT
[223.21, 132.59, 0.0, 523.8, 175.51]
ACR_DUE_MEMO_AMT
[0.0, 2346.43, 7020.57, 681.01, 14596.69]
ACR_MISC_MEMO_AMT
[0]
ACR_INT_RTL_YTD_AMT
[446.81, 132.59, 0.0, 3945.92, 1150.65]
ACR_INT_CASH_ADV_YTD_AMT
[0.0, 847.38, 1415.18, 21.37, 95.3]
BNS_BUCK_BAL
[0]
BNS_BUCK_USED
[0]
BNS_BUCK_RNG_ID
[1]
CRN_BAL_AMT_RNG_ID
[829, 846, 839, 854, 856]
PAST_DUE_AMT_RNG_ID
[839, 843, 842, 850, 840]
CR_LMT_AMT_RNG_ID
[34, 32, 33, 35, 31]
RTL_AMT
[21326.87, 9516.38, 0.0, 1368.93, 104206.19]
CASH_ADV_AMT
[0.0, -0.51, -148.86, -8.45, 21919.79]
MAIL_ORDR_AMT
[0.0, 640.93, 2854.0, 77100.0, 3000.0]
PAST_DUE_LT30_AMT
[0.0, 1000.0, 0.21, 3581.42, 4.89]
PAST_DUE_30_AMT
[0.0, 3413.11, 4980.11, 1769.41, 700.1]
PAST_DUE_60_AMT
[0.0, 7267.35, 1712.34, 732.56, 1142.67]
PAST_DUE_90_AMT
[0.0, 6930.02, 1769.41, 31953.25, 1142.67]
PAST_DUE_120_AMT
[0.0, 6606.19, 1712.34, 4389.42, 1105.81]
PAST_DUE_150_AMT
[0.0, 6276.08, 2379.29, 2284.57, 1142.67]
PAST_DUE_180_AMT
[0.0, 52571.19, 1105.81, 13171.53, 731.73]
PAST_DUE_210_AMT
[0.0, 51597.12, 77490.89, 30096.26, 45763.58]
CASH_ADV_FEE_AMT
[0.0, 600.0, 300.0, 750.0, 450.0]
CR_LMT_TEMP_EFF_DT
[nan, '2015-02-24', '2015-01-20', '2015-02-22', '2015-02-05']
CR_LMT_TEMP_END_DT
[nan, '2015-04-29', '2015-04-20', '2015-03-24', '2015-03-07']
IS_GOOD_PYMT_F
['Y', 'N']
DLQ_ST_ID
[0, 204, 202, 200, 460]
AR_SEG_SZ
['MI', 'PC', 'HN']